### ISSUE TITLE
Apartado 1: Modelado del Sistema

### ISSUE THREAD

**Issue by javierdesant** [javierdesant/Titanic-DB-Rescue#2]
# Apartado 1: Modelado del Sistema

### Descripción
Completar las tareas relacionadas con el modelado conceptual del sistema, el paso a tablas y la definición de elementos semánticos y dominios. Este apartado es crítico para establecer la base del proyecto.

### Tasks
- [x] #5
  _Nota: Es obligatorio usar esta notación; se suspenderá si se emplea otra._

- [x] Identificar y documentar todos los elementos de **"Semántica no contemplada"** detectados en el enunciado.

- [x] Definir los **dominios** de todos los atributos para las entidades:
  - Pasajeros
  - Cabinas
  - Cubiertas

- [x] Realizar el **paso a tablas** del modelo Entidad-Relación generado en la tarea anterior.

### Criterios de Finalización
- [x] Todos los diagramas y tablas deben estar documentados y revisados.
- [x] La semántica no contemplada debe estar definida con claridad.
- [x] Los dominios y restricciones de los atributos deben ser consistentes con el enunciado.

**Comment by Cafileiro** [comment]
Me pongo yo con la semántica no contemplada.

**Comment by Cafileiro** [comment]
Aquí esta un txt con lo que he podido encontrar de semántica no contemplada.
[SemanticaNC.txt](https://github.com/user-attachments/files/18136979/SemanticaNC.txt)
